spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: 12345678

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启后驼峰命名和下划线命名会自动转换

knife4j:
  enable: true
